# Generated by Django 4.1.3 on 2022-12-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('writer', models.CharField(max_length=120)),
                ('publication', models.CharField(max_length=120)),
                ('about', models.CharField(max_length=120)),
                ('file_1', models.FileField(default=None, max_length=1000, null=True, upload_to='Hello/')),
                ('buttona', models.FileField(default=None, max_length=1000, null=True, upload_to='Hello/')),
            ],
        ),
        
    ]
